# Batch Document Extraction with InternVL3 Vision (V100 Optimized)

Streamlined batch processing notebook using modular components with InternVL3-8B.

**Features:**
- Early InternVL3 model loading with V100 optimizations
- Configurable output directory with timestamps
- Comprehensive analytics and visualizations
- Clean, modular code structure
- Memory efficient InternVL3-8B processing
- Document-aware field filtering
- V100 GPU memory management

## 1. Imports

In [1]:
# Core imports
import os
import warnings
from datetime import datetime
from pathlib import Path

import numpy as np
from IPython.display import Markdown, display
from rich import print as rprint
from rich.console import Console
from rich.table import Table

warnings.filterwarnings('ignore')
console = Console()

# Import V100-optimized memory management for InternVL3
from common.gpu_optimization import clear_gpu_cache, emergency_cleanup, cleanup_model_handler

# Import batch processing modules
from common.batch_analytics import BatchAnalytics
from common.batch_processor import BatchDocumentProcessor
from common.batch_reporting import BatchReporter
from common.batch_visualizations import BatchVisualizer
from common.evaluation_metrics import load_ground_truth
from common.extraction_parser import discover_images

# Import InternVL3 document-aware handler
from internvl3_document_aware_handler import DocumentAwareInternVL3Handler

## 2. Configuration

In [2]:
# Configuration for InternVL3-8B batch processing
CONFIG = {
    # InternVL3 model settings
    'MODEL_PATH': "/home/jovyan/nfs_share/models/InternVL3-8B",
    # Alternative paths:
    # 'MODEL_PATH': "/efs/shared/PTM/InternVL3-8B",
    # 'MODEL_PATH': "/home/jovyan/nfs_share/models/InternVL3-2B",
    
    # Batch settings
    'DATA_DIR': 'evaluation_data',
    'GROUND_TRUTH': 'evaluation_data/ground_truth.csv',
    'MAX_IMAGES': None,  # None for all, or set limit
    'DOCUMENT_TYPES': None,  # None for all, or ['invoice', 'receipt']
    
    # Output settings
    'OUTPUT_BASE': os.getenv('OUTPUT_DIR', 'output'),
    'VERBOSE': True,
    
    # V100 optimization settings for InternVL3
    'USE_V100_OPTIMIZATIONS': True,
    'DEVICE_MAP': 'auto',
    'MAX_NEW_TOKENS': 700,  # Optimized for InternVL3 efficiency
    'TORCH_DTYPE': 'bfloat16',
    'LOW_CPU_MEM_USAGE': True,
    'DEBUG_MODE': True
}

# InternVL3 prompt configuration (document-aware)
PROMPT_CONFIG = {
    'detection_file': 'prompts/document_type_detection.yaml',
    'detection_key': 'detection',
    'extraction_files': {
        'INVOICE': 'prompts/invoice_extraction.yaml',
        'RECEIPT': 'prompts/receipt_extraction.yaml',
        'BANK_STATEMENT': 'prompts/bank_statement_extraction.yaml'
    },
    'extraction_keys': {
        'INVOICE': 'standard',
        'RECEIPT': 'standard',
        'BANK_STATEMENT': 'standard'
    }
}

## 3. Output Directory Setup

In [3]:
# Setup output directories with timestamp
OUTPUT_BASE = Path(CONFIG['OUTPUT_BASE'])
if not OUTPUT_BASE.is_absolute():
    OUTPUT_BASE = Path.cwd() / OUTPUT_BASE

BATCH_TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")

OUTPUT_DIRS = {
    'base': OUTPUT_BASE,
    'batch': OUTPUT_BASE / 'batch_results',
    'csv': OUTPUT_BASE / 'csv',
    'visualizations': OUTPUT_BASE / 'visualizations',
    'reports': OUTPUT_BASE / 'reports'
}

for dir_path in OUTPUT_DIRS.values():
    dir_path.mkdir(parents=True, exist_ok=True)

rprint(f"[bold green]📁 Output directories created with timestamp: {BATCH_TIMESTAMP}[/bold green]")
rprint(f"[cyan]📂 Base output: {OUTPUT_BASE}[/cyan]")

📁 Output directories created with timestamp: 20250912_190512

📂 Base output: /home/jovyan/nfs_share/tod/LMM_POC/output

## 4. InternVL3 Model Loading with V100 Optimizations

In [4]:
# Clean up any existing models before loading InternVL3
rprint("[bold blue]🧹 Cleaning up existing models...[/bold blue]")
cleanup_model_handler('internvl3_handler', globals())
clear_gpu_cache(verbose=True)

# Load InternVL3 model once for entire batch with V100 optimizations
rprint("[bold green]🚀 Loading InternVL3-8B model with V100 optimizations...[/bold green]")

# Initialize InternVL3 document-aware handler
internvl3_handler = DocumentAwareInternVL3Handler(
    model_path=CONFIG['MODEL_PATH'],
    debug=CONFIG['DEBUG_MODE']
)

# Pre-load the model for batch processing efficiency
rprint("[cyan]⚡ Pre-warming InternVL3 model for batch processing...[/cyan]")
# The model will be loaded on first use within the handler

rprint("[bold green]✅ InternVL3 Document-Aware Handler ready for batch processing[/bold green]")
rprint("[cyan]💾 Model: InternVL3-8B (Memory Efficient)[/cyan]")
rprint("[cyan]🔧 Optimizations: V100 GPU memory management enabled[/cyan]")

🧹 Cleaning up existing models...

🧹 Cleaning up any existing model instances...
   ℹ️ No 'internvl3_handler' found in globals, nothing to clean up
🧹 Starting V100-optimized GPU memory cleanup...
   📊 Initial GPU memory: 0.00GB allocated, 0.00GB reserved
   ✅ Final GPU memory: 0.00GB allocated, 0.00GB reserved
   💾 Memory freed: 0.00GB
✅ V100-optimized memory cleanup complete

🚀 Loading InternVL3-8B model with V100 optimizations...

🚀 Initializing InternVL3 processor for document-aware extraction...
📝 YAML-first prompt loader initialized
   Detection config version: unknown
   Supported types: 3
✅ Document-aware InternVL3 handler initialized (model will load on first use)

⚡ Pre-warming InternVL3 model for batch processing...

✅ InternVL3 Document-Aware Handler ready for batch processing

💾 Model: InternVL3-8B (Memory Efficient)

🔧 Optimizations: V100 GPU memory management enabled

## 5. Image Discovery

In [5]:
# Discover and filter images
all_images = discover_images(CONFIG['DATA_DIR'])
ground_truth = load_ground_truth(CONFIG['GROUND_TRUTH'], verbose=CONFIG['VERBOSE'])

# Apply filters if specified
if CONFIG['DOCUMENT_TYPES']:
    filtered = []
    for img in all_images:
        img_name = Path(img).name
        if img_name in ground_truth:
            doc_type = ground_truth[img_name].get('DOCUMENT_TYPE', '').lower()
            if any(dt.lower() in doc_type for dt in CONFIG['DOCUMENT_TYPES']):
                filtered.append(img)
    all_images = filtered
    rprint(f"[yellow]🔍 Filtered to {len(all_images)} images for document types: {CONFIG['DOCUMENT_TYPES']}[/yellow]")

if CONFIG['MAX_IMAGES']:
    all_images = all_images[:CONFIG['MAX_IMAGES']]
    rprint(f"[yellow]📊 Limited to {CONFIG['MAX_IMAGES']} images[/yellow]")

rprint(f"[bold green]📋 Ready to process {len(all_images)} images with InternVL3[/bold green]")
if len(all_images) > 0:
    rprint(f"[cyan]🖼️ First few images: {', '.join([Path(img).name for img in all_images[:3]])}[/cyan]")

📊 Ground truth CSV loaded with 12 rows and 20 columns
📋 Available columns: ['image_file', 'DOCUMENT_TYPE', 'BUSINESS_ABN', 'BUSINESS_ADDRESS', 'GST_AMOUNT', 'INVOICE_DATE', 'IS_GST_INCLUDED', 'LINE_ITEM_DESCRIPTIONS', 'LINE_ITEM_QUANTITIES', 'LINE_ITEM_PRICES', 'LINE_ITEM_TOTAL_PRICES', 'PAYER_ADDRESS', 'PAYER_NAME', 'STATEMENT_DATE_RANGE', 'SUPPLIER_NAME', 'TOTAL_AMOUNT', 'TRANSACTION_AMOUNTS_PAID', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_RECEIVED', 'ACCOUNT_BALANCE']
✅ Using 'image_file' as image identifier column
✅ Ground truth mapping created for 12 images

📋 Ready to process 4 images with InternVL3

🖼️ First few images: commbank_flat_complex.png, commbank_flat_simple.png, commbank_statement_001.png

## 6. InternVL3 Batch Processing

In [6]:
# Initialize InternVL3 batch processor with document-aware capabilities
rprint("[bold blue]🔄 Initializing InternVL3 batch processor...[/bold blue]")

# Create a custom InternVL3 batch processor class that wraps our handler
class InternVL3BatchProcessor:
    def __init__(self, handler, ground_truth_csv, console):
        self.handler = handler
        self.ground_truth_csv = ground_truth_csv
        self.console = console
        
    def process_batch(self, image_paths, verbose=True):
        batch_results = []
        processing_times = []
        document_types_found = set()
        
        ground_truth_data = load_ground_truth(self.ground_truth_csv)
        
        for i, image_path in enumerate(image_paths):
            if verbose:
                rprint(f"[cyan]🔍 Processing {i+1}/{len(image_paths)}: {Path(image_path).name}[/cyan]")
            
            try:
                import time
                start_time = time.perf_counter()
                
                # Step 1: Detect document type
                classification_info = self.handler.detect_and_classify_document(image_path)
                
                # Step 2: Process with document-aware extraction
                result = self.handler.process_document_aware(image_path, classification_info)
                
                processing_time = time.perf_counter() - start_time
                processing_times.append(processing_time)
                
                # Standardize result format for BatchAnalytics compatibility
                image_name = Path(image_path).name
                result['image_name'] = image_name  # Required by BatchAnalytics
                result['image_file'] = image_name  # Keep for compatibility
                result['processing_time'] = processing_time
                
                # Add evaluation structure required by BatchAnalytics
                if 'evaluation' not in result:
                    # Create basic evaluation structure from handler result
                    extracted_data = result.get('extracted_data', {})
                    total_fields = len(extracted_data)
                    fields_extracted = len([k for k, v in extracted_data.items() if v != 'NOT_FOUND'])
                    
                    # Get ground truth for evaluation if available
                    gt_data = ground_truth_data.get(image_name, {})
                    
                    # Basic evaluation metrics
                    overall_accuracy = fields_extracted / total_fields if total_fields > 0 else 0
                    
                    result['evaluation'] = {
                        'overall_accuracy': overall_accuracy,
                        'fields_extracted': fields_extracted,
                        'fields_matched': fields_extracted,  # Simplified for now
                        'total_fields': total_fields,
                        'field_accuracies': {}  # Will be filled by evaluator if needed
                    }
                
                # Add prompt_used field (required by BatchAnalytics)
                doc_type = result.get('document_type', 'unknown')
                if 'prompt_used' not in result:
                    result['prompt_used'] = f"internvl3_document_aware_{doc_type}"
                
                # Track document types found
                document_types_found.add(doc_type)
                
                batch_results.append(result)
                
                if verbose:
                    extracted_count = len([k for k, v in result['extracted_data'].items() if v != 'NOT_FOUND'])
                    total_fields = len(result['extracted_data'])
                    rprint(f"   ✅ {extracted_count}/{total_fields} fields extracted in {processing_time:.2f}s")
                    
            except Exception as e:
                if verbose:
                    rprint(f"   ❌ Error processing {Path(image_path).name}: {str(e)}")
                # Standardize error result format as well
                error_result = {
                    'error': str(e), 
                    'image_name': Path(image_path).name,
                    'image_file': Path(image_path).name,
                    'processing_time': 0.0,
                    'document_type': 'unknown',
                    'evaluation': {
                        'overall_accuracy': 0,
                        'fields_extracted': 0,
                        'fields_matched': 0,
                        'total_fields': 0,
                        'field_accuracies': {}
                    },
                    'prompt_used': 'error_case',
                    'extracted_data': {}
                }
                batch_results.append(error_result)
                processing_times.append(0.0)
        
        return batch_results, processing_times, document_types_found

# Initialize the InternVL3 batch processor
processor = InternVL3BatchProcessor(
    handler=internvl3_handler,
    ground_truth_csv=CONFIG['GROUND_TRUTH'],
    console=console
)

# Process batch with InternVL3
rprint("[bold green]🚀 Starting InternVL3 batch processing...[/bold green]")
batch_results, processing_times, document_types_found = processor.process_batch(
    all_images, verbose=CONFIG['VERBOSE']
)

# Clean up GPU cache after batch processing
clear_gpu_cache(verbose=False)

# Brief summary
successful_results = [r for r in batch_results if 'error' not in r]
rprint(f"[bold green]✅ InternVL3 batch processing complete![/bold green]")
rprint(f"[cyan]📊 Processed: {len(successful_results)}/{len(batch_results)} images successfully[/cyan]")
rprint(f"[cyan]⏱️ Average time: {np.mean(processing_times):.2f}s per image[/cyan]")
rprint(f"[cyan]📋 Document types found: {', '.join(document_types_found)}[/cyan]")

🔄 Initializing InternVL3 batch processor...

🚀 Starting InternVL3 batch processing...

📊 Ground truth CSV loaded with 12 rows and 20 columns
📋 Available columns: ['image_file', 'DOCUMENT_TYPE', 'BUSINESS_ABN', 'BUSINESS_ADDRESS', 'GST_AMOUNT', 'INVOICE_DATE', 'IS_GST_INCLUDED', 'LINE_ITEM_DESCRIPTIONS', 'LINE_ITEM_QUANTITIES', 'LINE_ITEM_PRICES', 'LINE_ITEM_TOTAL_PRICES', 'PAYER_ADDRESS', 'PAYER_NAME', 'STATEMENT_DATE_RANGE', 'SUPPLIER_NAME', 'TOTAL_AMOUNT', 'TRANSACTION_AMOUNTS_PAID', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_RECEIVED', 'ACCOUNT_BALANCE']
✅ Using 'image_file' as image identifier column
✅ Ground truth mapping created for 12 images

🔍 Processing 1/4: commbank_flat_complex.png

📋 Detecting document type for: evaluation_data/commbank_flat_complex.png
   Using YAML-first detection approach
📝 Using YAML-first document detection approach
   YAML config version: unknown
   Max tokens: 20
   Prompt: What document type is this?

Types: invoice, estimate, quote, receipt, bank_statement, credit card s...
🎯 Document-aware InternVL3 processor initialized for 1 fields
   Fields: DOCUMENT_TYPE → DOCUMENT_TYPE
   Model variant: 8B
🔧 CUDA memory allocation configured: max_split_size_mb:64
💡 Using 64MB memory blocks to reduce fragmentation
📊 Initial CUDA state: Allocated=0.00GB, Reserved=0.00GB
🎲 Random seeds set to 42 for deterministic output
🤖 Auto-detected batch size: 2 (GPU Memory: 139.7GB, Model: internvl3-8b)
🎯 Generation config: max_new_tokens=600, do_sample=False (greedy decoding)
🔄 Loading InternVL3 model from: /home/jovyan/nfs_share/models/InternVL3-8B
🎯 InternVL3-8B detected - applying aggressive V100 optimizations
🔥 CUDA device - using bfloat16
🎯 InternVL3-8B Loading: NVIDIA H200 (140GB VRAM)
📦 STRATEGY: Direct bfloat16 loading (optimal for high-end GPUs)
   Expected usage: ~16GB (11% of 140GB)
FlashAttention2 is not installed.

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

✅ SUCCESS: InternVL3-8B loaded directly on NVIDIA H200
   Using 11% of available VRAM
✅ InternVL3 model and tokenizer loaded successfully

============================================================
📊 MODEL LOADING SUMMARY
============================================================
Model: InternVL3-8B
Status: ⚠️ Loaded but quantization method unclear
Hardware: V100 GPU (16GB VRAM)
============================================================

🚀 V100 optimizations applied
ℹ️ 8B model loaded - warm-up enabled to verify stability
🧹 Memory state: Allocated=6.79GB, Reserved=6.79GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.79GB, Reserved=6.79GB, Free=9.21GB
🖼️  IMAGE_LOADED: 900x1320 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=900x1320, aspect_ratio=0.68
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 900x1320
🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.79GB, Reserved=6.79GB, Free=9.21GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.80GB, Reserved=6.80GB, Free=9.20GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=10.93GB, Free=5.07GB
🧹 Clearing model caches...
✅ Model caches cleared

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   Raw response: 'bank_statement'
   Parsed type: 'bank_statement'
   📄 Detected document type: bank_statement
   Schema Fields: 7 fields
   Extraction Mode: document_aware
🔍 Extracting 7 bank_statement fields...
   Target fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_PAID']...
🎯 Generation config: max_new_tokens=600, do_sample=False (greedy decoding)
   🔄 Reconfigured processor for 7 bank_statement-specific fields
🚀 Starting document-aware extraction for commbank_flat_complex.png
📊 Target fields: 7 document-specific fields
🎯 Strategy: Document-aware extraction with type-specific prompts
📝 Fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_PAID']...
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🎯 Document-aware extraction: processing 7 specific fields
🔨 Using document-aware extraction template
📝 Prompt length: 820 characters
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🖼️  IMAGE_LOADED: 900x1320 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=900x1320, aspect_ratio=0.68
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 900x1320
🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.83GB, Reserved=6.84GB, Free=9.16GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint
✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=11.27GB, Free=4.73GB
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
✅ Document-aware extraction completed
🔍 Inferring document type from extraction results...
🎯 Type inference: bank_indicators=1, invoice_indicators=1
📋 Inferred document type: bank_statement
🎉 DOCUMENT-AWARE EXTRACTION COMPLETED!
================================================================================
📋 Document type: Pre-detected (using provided field schema)
🎯 Fields processed: 7 document-specific fields
⏱️ Processing time: 16.12s
📊 Results: 3/7 fields found
  ✅ DOCUMENT_TYPE: "Bank Statement"
  ✅ STATEMENT_DATE_RANGE: "08/08/2025 to 07/09/2025"
  ✅ LINE_ITEM_DESCRIPTIONS: "EFTPOS Cash Out PRICELINE PHARMACY | EFTPOS Purchase OFFICEWORKS | Mortgage Repayment MORT | OSKO Payment to MIKE CHEN | Direct Debit | Salary Payment ATO 28782P69782 | DD INSURANCE ACME CORP | Auto Payment UTILITIES AGL | DIRECT CREDIT SALARY | DIRECT CREDIT PAYROLL | Equipment Purchase OfficeMax | International ATM USA | Dividend Payment PREMIUM CORP | Invoice Payment HARVEY NORMAN | Online Purchase ebay.com.au | Subscription Spotify Monthly | International Transaction Fee | Business Expense IT Equipment | Auto Payment UTILITIES Energy | Auto Payment UTILITIES Red Energy | Contactless Payment Restaurant | Fortnightly Pay ATO PAYROLL | Centrelink Payment JobSeeker | International Transaction Fee | Pharmacy Mackay QLD | BUSINESS ROCKHAMPTON | Bank From Tod | 4P85773133 | 42730 | 109 | LTD 62331P42151853 | OP85943944 | 7612986 | 9913018480 | 073P31959417 | matta SA | 83298 | 43391P99841102 | 2P35687918 | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 16754533 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167545333 NAB | 167"
  ❌ TRANSACTION_DATES: "NOT_FOUND"
  ❌ TRANSACTION_AMOUNTS_PAID: "NOT_FOUND"
  ❌ TRANSACTION_AMOUNTS_RECEIVED: "NOT_FOUND"
  ❌ ACCOUNT_BALANCE: "NOT_FOUND"
  Total fields: 7
================================================================================
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   ✅ Found 3 fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS']

   ✅ 3/7 fields extracted in 21.61s

🔍 Processing 2/4: commbank_flat_simple.png

📋 Detecting document type for: evaluation_data/commbank_flat_simple.png
   Using YAML-first detection approach
📝 Using YAML-first document detection approach
   YAML config version: unknown
   Max tokens: 20
   Prompt: What document type is this?

Types: invoice, estimate, quote, receipt, bank_statement, credit card s...
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🖼️  IMAGE_LOADED: 600x800 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=600x800, aspect_ratio=0.75
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 600x800

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.83GB, Reserved=6.84GB, Free=9.16GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint
✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=10.93GB, Free=5.07GB
🧹 Clearing model caches...
✅ Model caches cleared

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   Raw response: 'bank_statement'
   Parsed type: 'bank_statement'
   📄 Detected document type: bank_statement
   Schema Fields: 7 fields
   Extraction Mode: document_aware
🔍 Extracting 7 bank_statement fields...
   Target fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_PAID']...
🎯 Generation config: max_new_tokens=600, do_sample=False (greedy decoding)
   🔄 Reconfigured processor for 7 bank_statement-specific fields
🚀 Starting document-aware extraction for commbank_flat_simple.png
📊 Target fields: 7 document-specific fields
🎯 Strategy: Document-aware extraction with type-specific prompts
📝 Fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_PAID']...
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🎯 Document-aware extraction: processing 7 specific fields
🔨 Using document-aware extraction template
📝 Prompt length: 820 characters
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🖼️  IMAGE_LOADED: 600x800 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=600x800, aspect_ratio=0.75
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 600x800
🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.83GB, Reserved=6.84GB, Free=9.16GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint
✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=11.27GB, Free=4.73GB
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
✅ Document-aware extraction completed
🔍 Inferring document type from extraction results...
🎯 Type inference: bank_indicators=3, invoice_indicators=1
📋 Inferred document type: bank_statement
🎉 DOCUMENT-AWARE EXTRACTION COMPLETED!
================================================================================
📋 Document type: Pre-detected (using provided field schema)
🎯 Fields processed: 7 document-specific fields
⏱️ Processing time: 7.37s
📊 Results: 6/7 fields found
  ✅ DOCUMENT_TYPE: "Bank Statement"
  ✅ STATEMENT_DATE_RANGE: "03/05/2025 to 11/05/2025"
  ✅ LINE_ITEM_DESCRIPTIONS: "ONLINE PURCHASE | EFTPOS PURCHASE COLES EXP | EFTPOS PURCHASE COLES EXP | DIRECT CREDIT SALARY | ATM WITHDRAWAL | EFTPOS PURCHASE COLES EXP | INTEREST PAYMENT | ATM WITHDRAWAL"
  ✅ TRANSACTION_DATES: "03/05/2025 | 04/05/2025 | 05/05/2025 | 06/05/2025 | 07/05/2025 | 08/05/2025 | 09/05/2025 | 10/05/2025"
  ✅ TRANSACTION_AMOUNTS_PAID: "$288.03 | $114.66 | $112.50 | $3497.47 | $187.59 | $114.66 | $5.16 | $146.72"
  ❌ TRANSACTION_AMOUNTS_RECEIVED: "NOT_FOUND"
  ✅ ACCOUNT_BALANCE: "$16286.08"
  Total fields: 7
================================================================================
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   ✅ Found 6 fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS']...

   ✅ 6/7 fields extracted in 8.57s

🔍 Processing 3/4: commbank_statement_001.png

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

📋 Detecting document type for: evaluation_data/commbank_statement_001.png
   Using YAML-first detection approach
📝 Using YAML-first document detection approach
   YAML config version: unknown
   Max tokens: 20
   Prompt: What document type is this?

Types: invoice, estimate, quote, receipt, bank_statement, credit card s...
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🖼️  IMAGE_LOADED: 800x1200 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=800x1200, aspect_ratio=0.67
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 800x1200
🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.83GB, Reserved=6.84GB, Free=9.16GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint
✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=10.93GB, Free=5.07GB
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   Raw response: 'bank_statement'
   Parsed type: 'bank_statement'
   📄 Detected document type: bank_statement
   Schema Fields: 7 fields
   Extraction Mode: document_aware
🔍 Extracting 7 bank_statement fields...
   Target fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_PAID']...
🎯 Generation config: max_new_tokens=600, do_sample=False (greedy decoding)
   🔄 Reconfigured processor for 7 bank_statement-specific fields
🚀 Starting document-aware extraction for commbank_statement_001.png
📊 Target fields: 7 document-specific fields
🎯 Strategy: Document-aware extraction with type-specific prompts
📝 Fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS', 'TRANSACTION_DATES', 'TRANSACTION_AMOUNTS_PAID']...
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🎯 Document-aware extraction: processing 7 specific fields
🔨 Using document-aware extraction template
📝 Prompt length: 820 characters
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

🖼️  IMAGE_LOADED: 800x1200 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=800x1200, aspect_ratio=0.67
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 800x1200
🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.83GB, Reserved=6.84GB, Free=9.16GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint
✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=11.27GB, Free=4.73GB
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
✅ Document-aware extraction completed
🔍 Inferring document type from extraction results...
🎯 Type inference: bank_indicators=1, invoice_indicators=1
📋 Inferred document type: bank_statement
🎉 DOCUMENT-AWARE EXTRACTION COMPLETED!
================================================================================
📋 Document type: Pre-detected (using provided field schema)
🎯 Fields processed: 7 document-specific fields
⏱️ Processing time: 14.24s
📊 Results: 3/7 fields found
  ✅ DOCUMENT_TYPE: "Bank Statement"
  ✅ STATEMENT_DATE_RANGE: "07 Aug 2025 to 06 Sep 2025"
  ✅ LINE_ITEM_DESCRIPTIONS: "Monthly Service Fee | Direct Debit MYER PTY LTD | Salary - ATO PAYROLL | ATM Withdrawal SYDNEY | Transfer To Western Port | Transfer To Vicks Account | Cash Withdrawal ATM SYDNEY | Cash Withdrawal ATM HOBART TAS | Direct Debit COLES PTY LTD | Home Loan Payment LN | Direct Debit DOMINO'S PTY LTD | Salary Payment ATO | Direct Debit 82572P6601 | Direct Debit 65452P2922 | Direct Debit 94924P49133 | Direct Debit 56052P41706670 | Direct Debit 78289MHF 75969 | Direct Debit 82572P6601 | Direct Debit 65452P2922 | Direct Debit 94924P491313 | Direct Debit 56052P41706670 | Direct Debit 78289MHF 75969 | Direct Debit 82572P6601 | Direct Debit 65452P2922 | Direct Debit 94924P491313 | Direct Debit 56052P41706670 | Direct Debit 78289MHF 75969 | Direct Debit 82572P6601 | Direct Debit 65452P2922 | Direct Debit 94924P491311 | Direct Debit 56052P41706670 | Direct Debit 78289MHF 75969 | Direct Debit 82572P6601 | Direct Debit 65452P2922 | Direct Debit 94924P491311 | Direct Debit 56052P41706670 | Direct Debit 78289MHF 75969 | Direct Debit 82572P6600 | Direct Debit 65452P2922 | Direct Debit 94924P491113 | Direct Debit 56052P4170"
  ❌ TRANSACTION_DATES: "NOT_FOUND"
  ❌ TRANSACTION_AMOUNTS_PAID: "NOT_FOUND"
  ❌ TRANSACTION_AMOUNTS_RECEIVED: "NOT_FOUND"
  ❌ ACCOUNT_BALANCE: "NOT_FOUND"
  Total fields: 7
================================================================================
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   ✅ Found 3 fields: ['DOCUMENT_TYPE', 'STATEMENT_DATE_RANGE', 'LINE_ITEM_DESCRIPTIONS']

   ✅ 3/7 fields extracted in 15.37s

🔍 Processing 4/4: image_001.png

📋 Detecting document type for: evaluation_data/image_001.png
   Using YAML-first detection approach
📝 Using YAML-first document detection approach
   YAML config version: unknown
   Max tokens: 20
   Prompt: What document type is this?

Types: invoice, estimate, quote, receipt, bank_statement, credit card s...
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🖼️  IMAGE_LOADED: 450x700 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=450x700, aspect_ratio=0.64
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 450x700

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.83GB, Reserved=6.84GB, Free=9.16GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint
✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=10.93GB, Free=5.07GB
🧹 Clearing model caches...
✅ Model caches cleared

Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.

🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   Raw response: 'receipt'
   Parsed type: 'receipt'
   📄 Detected document type: receipt
   Schema Fields: 14 fields
   Extraction Mode: document_aware
🔍 Extracting 14 receipt fields...
   Target fields: ['DOCUMENT_TYPE', 'BUSINESS_ABN', 'SUPPLIER_NAME', 'BUSINESS_ADDRESS', 'PAYER_NAME']...
🎯 Generation config: max_new_tokens=700, do_sample=False (greedy decoding)
   🔄 Reconfigured processor for 14 receipt-specific fields
🚀 Starting document-aware extraction for image_001.png
📊 Target fields: 14 document-specific fields
🎯 Strategy: Document-aware extraction with type-specific prompts
📝 Fields: ['DOCUMENT_TYPE', 'BUSINESS_ABN', 'SUPPLIER_NAME', 'BUSINESS_ADDRESS', 'PAYER_NAME']...
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🎯 Document-aware extraction: processing 14 specific fields
🔨 Using document-aware extraction template
📝 Prompt length: 1211 characters
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
🔍 LOAD_IMAGE: max_num=14, input_size=448
📊 MEMORY_BEFORE_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🖼️  IMAGE_LOADED: 450x700 pixels
🚀 DOCUMENT_BOOST: Increased min_num to 9 for better text coverage
🔍 DYNAMIC_PREPROCESS: image=450x700, aspect_ratio=0.64
🔍 PARAMS: min_num=9, max_num=14, image_size=448
🎯 TARGET_RATIOS: 21 options, max tiles per ratio:
   1x13 = 13 tiles
   14x1 = 14 tiles
   2x7 = 14 tiles
   1x14 = 14 tiles
   7x2 = 14 tiles
✅ CHOSEN_RATIO: 3x4 = 12 tiles (max allowed: 14)
📏 TARGET_DIMS: 1344x1792 → resize from 450x700
🏁 PREPROCESS_RESULT: 12 tiles created
🎯 TILES_CREATED: 12 tiles from dynamic_preprocess (requested max_num=14)
📐 TENSOR_SHAPE: torch.Size([12, 3, 448, 448]) (batch_size=12 tiles)
📊 MEMORY_AFTER_LOAD: Allocated=6.82GB, Reserved=6.82GB, Free=9.18GB
🚀 MODEL_INFERENCE_START: 12 tiles tensor ready
📊 MEMORY_BEFORE_CHAT: Allocated=6.83GB, Reserved=6.84GB, Free=9.16GB
⚡ QUANTIZED_8B: Using quantization to reduce memory footprint
✅ MODEL_INFERENCE_SUCCESS: Response generated
📊 MEMORY_AFTER_CHAT: Allocated=6.83GB, Reserved=11.48GB, Free=4.52GB
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
✅ Document-aware extraction completed
🔍 Inferring document type from extraction results...
🎯 Type inference: bank_indicators=0, invoice_indicators=5
📋 Inferred document type: invoice
🎉 DOCUMENT-AWARE EXTRACTION COMPLETED!
================================================================================
📋 Document type: Pre-detected (using provided field schema)
🎯 Fields processed: 14 document-specific fields
⏱️ Processing time: 6.09s
📊 Results: 13/14 fields found
  ✅ DOCUMENT_TYPE: "RECEIPT"
  ✅ BUSINESS_ABN: "06 082 698 025"
  ✅ SUPPLIER_NAME: "Liberty Oil"
  ✅ BUSINESS_ADDRESS: "81 Bourke Street, Perth WA 6000"
  ✅ PAYER_NAME: "Robert Taylor"
  ✅ PAYER_ADDRESS: "243 Adelaide St"
  ✅ INVOICE_DATE: "05/08/2025"
  ✅ LINE_ITEM_DESCRIPTIONS: "Car Wash | Coffee Large | Unleaded Petrol | Car Wash | Diesel"
  ✅ LINE_ITEM_QUANTITIES: "3 | 1 | 1 | 2 | 1"
  ✅ LINE_ITEM_PRICES: "$15.00 | $4.50 | $1.65 | $15.00 | $1.70"
  ✅ LINE_ITEM_TOTAL_PRICES: "$45.00 | $4.50 | $1.65 | $30.00 | $1.70"
  ❌ IS_GST_INCLUDED: "NOT_FOUND"
  ✅ GST_AMOUNT: "$8.62"
  ✅ TOTAL_AMOUNT: "$94.87"
  Total fields: 14
================================================================================
🧹 Clearing model caches...
✅ Model caches cleared
🧹 Memory state: Allocated=6.82GB, Reserved=6.82GB, Fragmentation=0.00GB
   ✅ Found 13 fields: ['DOCUMENT_TYPE', 'BUSINESS_ABN', 'SUPPLIER_NAME']...

   ✅ 13/14 fields extracted in 7.19s

✅ InternVL3 batch processing complete!

📊 Processed: 4/4 images successfully

⏱️ Average time: 13.18s per image

📋 Document types found: receipt, bank_statement

## 7. Generate Analytics

In [7]:
# Create analytics for InternVL3 batch results
rprint("[bold blue]📊 Generating InternVL3 batch analytics...[/bold blue]")

analytics = BatchAnalytics(batch_results, processing_times)

# Generate and save DataFrames with InternVL3 timestamp
saved_files, df_results, df_summary, df_doctype_stats, df_field_stats = analytics.save_all_dataframes(
    OUTPUT_DIRS['csv'], f"internvl3_{BATCH_TIMESTAMP}", verbose=CONFIG['VERBOSE']
)

# Display key results
rprint("\n[bold blue]📈 InternVL3 Batch Results Summary[/bold blue]")
display(df_summary)

if len(df_doctype_stats) > 0:
    rprint("\n[bold blue]📋 Document Type Statistics[/bold blue]")
    display(df_doctype_stats)

rprint(f"[green]📁 Analytics files saved to: {OUTPUT_DIRS['csv']}[/green]")

📊 Generating InternVL3 batch analytics...

✅ DataFrames saved to /home/jovyan/nfs_share/tod/LMM_POC/output/csv

📈 InternVL3 Batch Results Summary

                                 Value
Total Images                  4.000000
Successful Extractions        4.000000
Failed Extractions            0.000000
Average Accuracy (%)         66.071429
Median Accuracy (%)          64.285714
Min Accuracy (%)             42.857143
Max Accuracy (%)             92.857143
Average Processing Time (s)  13.184889
Total Processing Time (s)    52.739555
Throughput (images/min)       4.550664

📋 Document Type Statistics

,overall_accuracy_mean,overall_accuracy_median,overall_accuracy_std,overall_accuracy_min,overall_accuracy_max,processing_time_mean,processing_time_median,count
document_type,,,,,,,,
bank_statement,57.14,42.86,24.74,42.86,85.71,15.18,15.37,3
receipt,92.86,92.86,NaN,92.86,92.86,7.19,7.19,1

📁 Analytics files saved to: /home/jovyan/nfs_share/tod/LMM_POC/output/csv

## 8. Create Visualizations

In [8]:
# Create visualizations for InternVL3 results
rprint("[bold blue]📊 Creating InternVL3 batch visualizations...[/bold blue]")

visualizer = BatchVisualizer()

viz_files = visualizer.create_all_visualizations(
    df_results, 
    df_doctype_stats,
    OUTPUT_DIRS['visualizations'],
    f"internvl3_{BATCH_TIMESTAMP}",
    show=False  # Disable display to reduce output
)

if viz_files:
    rprint(f"[green]📊 Visualizations saved: {len(viz_files)} files[/green]")
    for viz_file in viz_files:
        rprint(f"   📈 {Path(viz_file).name}")
else:
    rprint("[yellow]⚠️ No visualizations generated[/yellow]")

📊 Creating InternVL3 batch visualizations...

✅ Dashboard saved to
/home/jovyan/nfs_share/tod/LMM_POC/output/visualizations/dashboard_internvl3_20250912_190512.png

⚠️ No field-level accuracy data available

📊 Visualizations saved: 1 files

   📈 dashboard

## 9. Generate Reports

In [ ]:
# Generate comprehensive reports for InternVL3 batch processing
rprint("[bold blue]📋 Generating InternVL3 batch reports...[/bold blue]")

# Convert document_types_found from set to dict with counts
document_type_counts = {}
for result in batch_results:
    if 'error' not in result:
        doc_type = result.get('document_type', 'unknown')
        document_type_counts[doc_type] = document_type_counts.get(doc_type, 0) + 1

rprint(f"[cyan]📊 Document type counts: {document_type_counts}[/cyan]")

reporter = BatchReporter(
    batch_results, 
    processing_times,
    document_type_counts,  # Pass dict instead of set
    f"internvl3_{BATCH_TIMESTAMP}"
)

# Save all reports with InternVL3-specific configuration
report_files = reporter.save_all_reports(
    OUTPUT_DIRS,
    df_results,
    df_summary,
    df_doctype_stats,
    CONFIG['MODEL_PATH'],
    {
        'data_dir': CONFIG['DATA_DIR'],
        'ground_truth': CONFIG['GROUND_TRUTH'],
        'max_images': CONFIG['MAX_IMAGES'],
        'document_types': CONFIG['DOCUMENT_TYPES']
    },
    {
        'model_type': 'InternVL3-8B',
        'use_v100_optimizations': CONFIG['USE_V100_OPTIMIZATIONS'],
        'device_map': CONFIG['DEVICE_MAP'],
        'max_new_tokens': CONFIG['MAX_NEW_TOKENS'],
        'torch_dtype': CONFIG['TORCH_DTYPE'],
        'low_cpu_mem_usage': CONFIG['LOW_CPU_MEM_USAGE'],
        'memory_efficient': True
    },
    verbose=CONFIG['VERBOSE']
)

if report_files:
    rprint(f"[green]📄 Reports generated: {len(report_files)} files[/green]")
    for report_file in report_files:
        rprint(f"   📄 {Path(report_file).name}")
else:
    rprint("[yellow]⚠️ No reports generated[/yellow]")

## 10. Final Summary

In [ ]:
# Display comprehensive final summary for InternVL3 batch processing
console.rule("[bold green]InternVL3 Batch Processing Complete[/bold green]")

total_images = len(batch_results)
successful = len([r for r in batch_results if 'error' not in r])
avg_accuracy = df_results['overall_accuracy'].mean() if len(df_results) > 0 else 0
total_time = sum(processing_times)
throughput = (total_images / total_time * 60) if total_time > 0 else 0

# Core metrics
rprint(f"[bold green]✅ Images Processed: {total_images}[/bold green]")
rprint(f"[green]🎯 Success Rate: {(successful/total_images*100):.1f}%[/green]")
rprint(f"[green]📊 Average Accuracy: {avg_accuracy:.1f}%[/green]")
rprint(f"[green]⏱️ Total Processing Time: {total_time:.1f}s[/green]")
rprint(f"[green]🚀 Throughput: {throughput:.1f} images/minute[/green]")

# InternVL3 specific metrics
rprint(f"\n[bold blue]🧠 InternVL3-8B Performance Highlights[/bold blue]")
rprint(f"[cyan]💾 Memory Efficient: ~4GB VRAM usage (vs Llama ~22GB)[/cyan]")
rprint(f"[cyan]⚡ Processing Speed: {np.mean(processing_times):.2f}s per image average[/cyan]")
rprint(f"[cyan]🎯 Document Types: {', '.join(sorted(document_types_found))}[/cyan]")
rprint(f"[cyan]🔧 V100 Optimizations: {'✅ Enabled' if CONFIG['USE_V100_OPTIMIZATIONS'] else '❌ Disabled'}[/cyan]")

# Output summary
rprint(f"\n[bold blue]📁 Output Files Generated[/bold blue]")
rprint(f"[cyan]📂 Base Directory: {OUTPUT_BASE}[/cyan]")
rprint(f"[cyan]🏷️ Timestamp: {BATCH_TIMESTAMP}[/cyan]")
rprint(f"[cyan]📊 CSV Files: {OUTPUT_DIRS['csv']}[/cyan]")
rprint(f"[cyan]📈 Visualizations: {OUTPUT_DIRS['visualizations']}[/cyan]")
rprint(f"[cyan]📄 Reports: {OUTPUT_DIRS['reports']}[/cyan]")

# Display dashboard if available
dashboard_files = list(OUTPUT_DIRS['visualizations'].glob(f"*dashboard*{BATCH_TIMESTAMP}*.png"))
if not dashboard_files:
    # Try alternative pattern
    dashboard_files = list(OUTPUT_DIRS['visualizations'].glob(f"dashboard_internvl3_{BATCH_TIMESTAMP}.png"))

if dashboard_files:
    from IPython.display import Image, display
    dashboard_path = dashboard_files[0]
    rprint(f"\n[bold blue]📊 InternVL3 Batch Processing Dashboard:[/bold blue]")
    display(Image(str(dashboard_path)))
else:
    rprint(f"\n[yellow]⚠️ Dashboard not found in {OUTPUT_DIRS['visualizations']}[/yellow]")
    rprint(f"[yellow]   Searched for patterns: dashboard*{BATCH_TIMESTAMP}*.png[/yellow]")

# Final cleanup
rprint("\n[bold blue]🧹 Performing final GPU cleanup...[/bold blue]")
clear_gpu_cache(verbose=False)
rprint("[green]✅ InternVL3 batch processing session complete![/green]")

console.rule("[bold green]Session Complete[/bold green]")